/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.warehouse.AddMaterialItemsRequest', null, global);
goog.exportSymbol('proto.warehouse.AddMaterialItemsResponse', null, global);
goog.exportSymbol('proto.warehouse.AddMaterialTypeRequest', null, global);
goog.exportSymbol('proto.warehouse.AddMaterialTypeResponse', null, global);
goog.exportSymbol('proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest', null, global);
goog.exportSymbol('proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse', null, global);
goog.exportSymbol('proto.warehouse.AddWarehouseRequest', null, global);
goog.exportSymbol('proto.warehouse.AddWarehouseResponse', null, global);
goog.exportSymbol('proto.warehouse.MaterialItem', null, global);
goog.exportSymbol('proto.warehouse.MaterialSpecification', null, global);
goog.exportSymbol('proto.warehouse.MaterialState', null, global);
goog.exportSymbol('proto.warehouse.MaterialType', null, global);
goog.exportSymbol('proto.warehouse.ProductType', null, global);
goog.exportSymbol('proto.warehouse.SetOrderForMaterialItemsRequest', null, global);
goog.exportSymbol('proto.warehouse.SetOrderForMaterialItemsResponse', null, global);
goog.exportSymbol('proto.warehouse.Warehouse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.warehouse.AddMaterialTypeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.warehouse.AddMaterialTypeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.warehouse.AddMaterialTypeRequest.displayName = 'proto.warehouse.AddMaterialTypeRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.warehouse.AddMaterialTypeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.warehouse.AddMaterialTypeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.warehouse.AddMaterialTypeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddMaterialTypeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.warehouse.AddMaterialTypeRequest}
 */
proto.warehouse.AddMaterialTypeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.warehouse.AddMaterialTypeRequest;
  return proto.warehouse.AddMaterialTypeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.warehouse.AddMaterialTypeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.warehouse.AddMaterialTypeRequest}
 */
proto.warehouse.AddMaterialTypeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.warehouse.AddMaterialTypeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.warehouse.AddMaterialTypeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.warehouse.AddMaterialTypeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddMaterialTypeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.warehouse.AddMaterialTypeRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.warehouse.AddMaterialTypeRequest.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.warehouse.AddMaterialTypeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.warehouse.AddMaterialTypeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.warehouse.AddMaterialTypeResponse.displayName = 'proto.warehouse.AddMaterialTypeResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.warehouse.AddMaterialTypeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.warehouse.AddMaterialTypeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.warehouse.AddMaterialTypeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddMaterialTypeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.warehouse.AddMaterialTypeResponse}
 */
proto.warehouse.AddMaterialTypeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.warehouse.AddMaterialTypeResponse;
  return proto.warehouse.AddMaterialTypeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.warehouse.AddMaterialTypeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.warehouse.AddMaterialTypeResponse}
 */
proto.warehouse.AddMaterialTypeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.warehouse.AddMaterialTypeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.warehouse.AddMaterialTypeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.warehouse.AddMaterialTypeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddMaterialTypeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.warehouse.AddMaterialTypeResponse.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.warehouse.AddMaterialTypeResponse.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.warehouse.AddMaterialTypeResponse.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.warehouse.AddMaterialTypeResponse.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.warehouse.AddMaterialItemsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.warehouse.AddMaterialItemsRequest.repeatedFields_, null);
};
goog.inherits(proto.warehouse.AddMaterialItemsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.warehouse.AddMaterialItemsRequest.displayName = 'proto.warehouse.AddMaterialItemsRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.warehouse.AddMaterialItemsRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.warehouse.AddMaterialItemsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.warehouse.AddMaterialItemsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.warehouse.AddMaterialItemsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddMaterialItemsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    materialitemsList: jspb.Message.toObjectList(msg.getMaterialitemsList(),
    proto.warehouse.MaterialItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.warehouse.AddMaterialItemsRequest}
 */
proto.warehouse.AddMaterialItemsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.warehouse.AddMaterialItemsRequest;
  return proto.warehouse.AddMaterialItemsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.warehouse.AddMaterialItemsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.warehouse.AddMaterialItemsRequest}
 */
proto.warehouse.AddMaterialItemsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.warehouse.MaterialItem;
      reader.readMessage(value,proto.warehouse.MaterialItem.deserializeBinaryFromReader);
      msg.addMaterialitems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.warehouse.AddMaterialItemsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.warehouse.AddMaterialItemsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.warehouse.AddMaterialItemsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddMaterialItemsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMaterialitemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.warehouse.MaterialItem.serializeBinaryToWriter
    );
  }
};


/**
 * repeated MaterialItem materialItems = 1;
 * @return {!Array<!proto.warehouse.MaterialItem>}
 */
proto.warehouse.AddMaterialItemsRequest.prototype.getMaterialitemsList = function() {
  return /** @type{!Array<!proto.warehouse.MaterialItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.warehouse.MaterialItem, 1));
};


/** @param {!Array<!proto.warehouse.MaterialItem>} value */
proto.warehouse.AddMaterialItemsRequest.prototype.setMaterialitemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.warehouse.MaterialItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.warehouse.MaterialItem}
 */
proto.warehouse.AddMaterialItemsRequest.prototype.addMaterialitems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.warehouse.MaterialItem, opt_index);
};


proto.warehouse.AddMaterialItemsRequest.prototype.clearMaterialitemsList = function() {
  this.setMaterialitemsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.warehouse.AddMaterialItemsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.warehouse.AddMaterialItemsResponse.repeatedFields_, null);
};
goog.inherits(proto.warehouse.AddMaterialItemsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.warehouse.AddMaterialItemsResponse.displayName = 'proto.warehouse.AddMaterialItemsResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.warehouse.AddMaterialItemsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.warehouse.AddMaterialItemsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.warehouse.AddMaterialItemsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.warehouse.AddMaterialItemsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddMaterialItemsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    materialitemsList: jspb.Message.toObjectList(msg.getMaterialitemsList(),
    proto.warehouse.MaterialItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.warehouse.AddMaterialItemsResponse}
 */
proto.warehouse.AddMaterialItemsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.warehouse.AddMaterialItemsResponse;
  return proto.warehouse.AddMaterialItemsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.warehouse.AddMaterialItemsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.warehouse.AddMaterialItemsResponse}
 */
proto.warehouse.AddMaterialItemsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.warehouse.MaterialItem;
      reader.readMessage(value,proto.warehouse.MaterialItem.deserializeBinaryFromReader);
      msg.addMaterialitems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.warehouse.AddMaterialItemsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.warehouse.AddMaterialItemsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.warehouse.AddMaterialItemsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddMaterialItemsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMaterialitemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.warehouse.MaterialItem.serializeBinaryToWriter
    );
  }
};


/**
 * repeated MaterialItem materialItems = 1;
 * @return {!Array<!proto.warehouse.MaterialItem>}
 */
proto.warehouse.AddMaterialItemsResponse.prototype.getMaterialitemsList = function() {
  return /** @type{!Array<!proto.warehouse.MaterialItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.warehouse.MaterialItem, 1));
};


/** @param {!Array<!proto.warehouse.MaterialItem>} value */
proto.warehouse.AddMaterialItemsResponse.prototype.setMaterialitemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.warehouse.MaterialItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.warehouse.MaterialItem}
 */
proto.warehouse.AddMaterialItemsResponse.prototype.addMaterialitems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.warehouse.MaterialItem, opt_index);
};


proto.warehouse.AddMaterialItemsResponse.prototype.clearMaterialitemsList = function() {
  this.setMaterialitemsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.warehouse.AddWarehouseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.warehouse.AddWarehouseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.warehouse.AddWarehouseRequest.displayName = 'proto.warehouse.AddWarehouseRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.warehouse.AddWarehouseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.warehouse.AddWarehouseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.warehouse.AddWarehouseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddWarehouseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    warehouse: (f = msg.getWarehouse()) && proto.warehouse.Warehouse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.warehouse.AddWarehouseRequest}
 */
proto.warehouse.AddWarehouseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.warehouse.AddWarehouseRequest;
  return proto.warehouse.AddWarehouseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.warehouse.AddWarehouseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.warehouse.AddWarehouseRequest}
 */
proto.warehouse.AddWarehouseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.warehouse.Warehouse;
      reader.readMessage(value,proto.warehouse.Warehouse.deserializeBinaryFromReader);
      msg.setWarehouse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.warehouse.AddWarehouseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.warehouse.AddWarehouseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.warehouse.AddWarehouseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddWarehouseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWarehouse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.warehouse.Warehouse.serializeBinaryToWriter
    );
  }
};


/**
 * optional Warehouse warehouse = 1;
 * @return {?proto.warehouse.Warehouse}
 */
proto.warehouse.AddWarehouseRequest.prototype.getWarehouse = function() {
  return /** @type{?proto.warehouse.Warehouse} */ (
    jspb.Message.getWrapperField(this, proto.warehouse.Warehouse, 1));
};


/** @param {?proto.warehouse.Warehouse|undefined} value */
proto.warehouse.AddWarehouseRequest.prototype.setWarehouse = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.warehouse.AddWarehouseRequest.prototype.clearWarehouse = function() {
  this.setWarehouse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.warehouse.AddWarehouseRequest.prototype.hasWarehouse = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.warehouse.AddWarehouseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.warehouse.AddWarehouseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.warehouse.AddWarehouseResponse.displayName = 'proto.warehouse.AddWarehouseResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.warehouse.AddWarehouseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.warehouse.AddWarehouseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.warehouse.AddWarehouseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddWarehouseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    warehouse: (f = msg.getWarehouse()) && proto.warehouse.Warehouse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.warehouse.AddWarehouseResponse}
 */
proto.warehouse.AddWarehouseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.warehouse.AddWarehouseResponse;
  return proto.warehouse.AddWarehouseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.warehouse.AddWarehouseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.warehouse.AddWarehouseResponse}
 */
proto.warehouse.AddWarehouseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.warehouse.Warehouse;
      reader.readMessage(value,proto.warehouse.Warehouse.deserializeBinaryFromReader);
      msg.setWarehouse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.warehouse.AddWarehouseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.warehouse.AddWarehouseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.warehouse.AddWarehouseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddWarehouseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWarehouse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.warehouse.Warehouse.serializeBinaryToWriter
    );
  }
};


/**
 * optional Warehouse warehouse = 1;
 * @return {?proto.warehouse.Warehouse}
 */
proto.warehouse.AddWarehouseResponse.prototype.getWarehouse = function() {
  return /** @type{?proto.warehouse.Warehouse} */ (
    jspb.Message.getWrapperField(this, proto.warehouse.Warehouse, 1));
};


/** @param {?proto.warehouse.Warehouse|undefined} value */
proto.warehouse.AddWarehouseResponse.prototype.setWarehouse = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.warehouse.AddWarehouseResponse.prototype.clearWarehouse = function() {
  this.setWarehouse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.warehouse.AddWarehouseResponse.prototype.hasWarehouse = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.repeatedFields_, null);
};
goog.inherits(proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.displayName = 'proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    producttype: (f = msg.getProducttype()) && proto.warehouse.ProductType.toObject(includeInstance, f),
    materialspecsList: jspb.Message.toObjectList(msg.getMaterialspecsList(),
    proto.warehouse.MaterialSpecification.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest;
  return proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.warehouse.ProductType;
      reader.readMessage(value,proto.warehouse.ProductType.deserializeBinaryFromReader);
      msg.setProducttype(value);
      break;
    case 2:
      var value = new proto.warehouse.MaterialSpecification;
      reader.readMessage(value,proto.warehouse.MaterialSpecification.deserializeBinaryFromReader);
      msg.addMaterialspecs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProducttype();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.warehouse.ProductType.serializeBinaryToWriter
    );
  }
  f = message.getMaterialspecsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.warehouse.MaterialSpecification.serializeBinaryToWriter
    );
  }
};


/**
 * optional ProductType productType = 1;
 * @return {?proto.warehouse.ProductType}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.prototype.getProducttype = function() {
  return /** @type{?proto.warehouse.ProductType} */ (
    jspb.Message.getWrapperField(this, proto.warehouse.ProductType, 1));
};


/** @param {?proto.warehouse.ProductType|undefined} value */
proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.prototype.setProducttype = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.prototype.clearProducttype = function() {
  this.setProducttype(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.prototype.hasProducttype = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated MaterialSpecification materialSpecs = 2;
 * @return {!Array<!proto.warehouse.MaterialSpecification>}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.prototype.getMaterialspecsList = function() {
  return /** @type{!Array<!proto.warehouse.MaterialSpecification>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.warehouse.MaterialSpecification, 2));
};


/** @param {!Array<!proto.warehouse.MaterialSpecification>} value */
proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.prototype.setMaterialspecsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.warehouse.MaterialSpecification=} opt_value
 * @param {number=} opt_index
 * @return {!proto.warehouse.MaterialSpecification}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.prototype.addMaterialspecs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.warehouse.MaterialSpecification, opt_index);
};


proto.warehouse.AddProductTypeAndMaterialSpecificationsRequest.prototype.clearMaterialspecsList = function() {
  this.setMaterialspecsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.repeatedFields_, null);
};
goog.inherits(proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.displayName = 'proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    producttype: (f = msg.getProducttype()) && proto.warehouse.ProductType.toObject(includeInstance, f),
    materialspecsList: jspb.Message.toObjectList(msg.getMaterialspecsList(),
    proto.warehouse.MaterialSpecification.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse;
  return proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.warehouse.ProductType;
      reader.readMessage(value,proto.warehouse.ProductType.deserializeBinaryFromReader);
      msg.setProducttype(value);
      break;
    case 2:
      var value = new proto.warehouse.MaterialSpecification;
      reader.readMessage(value,proto.warehouse.MaterialSpecification.deserializeBinaryFromReader);
      msg.addMaterialspecs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProducttype();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.warehouse.ProductType.serializeBinaryToWriter
    );
  }
  f = message.getMaterialspecsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.warehouse.MaterialSpecification.serializeBinaryToWriter
    );
  }
};


/**
 * optional ProductType productType = 1;
 * @return {?proto.warehouse.ProductType}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.prototype.getProducttype = function() {
  return /** @type{?proto.warehouse.ProductType} */ (
    jspb.Message.getWrapperField(this, proto.warehouse.ProductType, 1));
};


/** @param {?proto.warehouse.ProductType|undefined} value */
proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.prototype.setProducttype = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.prototype.clearProducttype = function() {
  this.setProducttype(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.prototype.hasProducttype = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated MaterialSpecification materialSpecs = 2;
 * @return {!Array<!proto.warehouse.MaterialSpecification>}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.prototype.getMaterialspecsList = function() {
  return /** @type{!Array<!proto.warehouse.MaterialSpecification>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.warehouse.MaterialSpecification, 2));
};


/** @param {!Array<!proto.warehouse.MaterialSpecification>} value */
proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.prototype.setMaterialspecsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.warehouse.MaterialSpecification=} opt_value
 * @param {number=} opt_index
 * @return {!proto.warehouse.MaterialSpecification}
 */
proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.prototype.addMaterialspecs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.warehouse.MaterialSpecification, opt_index);
};


proto.warehouse.AddProductTypeAndMaterialSpecificationsResponse.prototype.clearMaterialspecsList = function() {
  this.setMaterialspecsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.warehouse.SetOrderForMaterialItemsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.warehouse.SetOrderForMaterialItemsRequest.repeatedFields_, null);
};
goog.inherits(proto.warehouse.SetOrderForMaterialItemsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.warehouse.SetOrderForMaterialItemsRequest.displayName = 'proto.warehouse.SetOrderForMaterialItemsRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.warehouse.SetOrderForMaterialItemsRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.warehouse.SetOrderForMaterialItemsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.warehouse.SetOrderForMaterialItemsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.warehouse.SetOrderForMaterialItemsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.SetOrderForMaterialItemsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    orderserial: jspb.Message.getFieldWithDefault(msg, 1, ""),
    materialitemidsList: jspb.Message.getRepeatedField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.warehouse.SetOrderForMaterialItemsRequest}
 */
proto.warehouse.SetOrderForMaterialItemsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.warehouse.SetOrderForMaterialItemsRequest;
  return proto.warehouse.SetOrderForMaterialItemsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.warehouse.SetOrderForMaterialItemsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.warehouse.SetOrderForMaterialItemsRequest}
 */
proto.warehouse.SetOrderForMaterialItemsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderserial(value);
      break;
    case 2:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setMaterialitemidsList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.warehouse.SetOrderForMaterialItemsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.warehouse.SetOrderForMaterialItemsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.warehouse.SetOrderForMaterialItemsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.SetOrderForMaterialItemsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrderserial();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMaterialitemidsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      2,
      f
    );
  }
};


/**
 * optional string orderSerial = 1;
 * @return {string}
 */
proto.warehouse.SetOrderForMaterialItemsRequest.prototype.getOrderserial = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.warehouse.SetOrderForMaterialItemsRequest.prototype.setOrderserial = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated int32 materialItemIds = 2;
 * @return {!Array<number>}
 */
proto.warehouse.SetOrderForMaterialItemsRequest.prototype.getMaterialitemidsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<number>} value */
proto.warehouse.SetOrderForMaterialItemsRequest.prototype.setMaterialitemidsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.warehouse.SetOrderForMaterialItemsRequest.prototype.addMaterialitemids = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.warehouse.SetOrderForMaterialItemsRequest.prototype.clearMaterialitemidsList = function() {
  this.setMaterialitemidsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.warehouse.SetOrderForMaterialItemsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.warehouse.SetOrderForMaterialItemsResponse.repeatedFields_, null);
};
goog.inherits(proto.warehouse.SetOrderForMaterialItemsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.warehouse.SetOrderForMaterialItemsResponse.displayName = 'proto.warehouse.SetOrderForMaterialItemsResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.warehouse.SetOrderForMaterialItemsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.warehouse.SetOrderForMaterialItemsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.warehouse.SetOrderForMaterialItemsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.warehouse.SetOrderForMaterialItemsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.SetOrderForMaterialItemsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    materialitemsList: jspb.Message.toObjectList(msg.getMaterialitemsList(),
    proto.warehouse.MaterialItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.warehouse.SetOrderForMaterialItemsResponse}
 */
proto.warehouse.SetOrderForMaterialItemsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.warehouse.SetOrderForMaterialItemsResponse;
  return proto.warehouse.SetOrderForMaterialItemsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.warehouse.SetOrderForMaterialItemsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.warehouse.SetOrderForMaterialItemsResponse}
 */
proto.warehouse.SetOrderForMaterialItemsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.warehouse.MaterialItem;
      reader.readMessage(value,proto.warehouse.MaterialItem.deserializeBinaryFromReader);
      msg.addMaterialitems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.warehouse.SetOrderForMaterialItemsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.warehouse.SetOrderForMaterialItemsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.warehouse.SetOrderForMaterialItemsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.SetOrderForMaterialItemsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMaterialitemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.warehouse.MaterialItem.serializeBinaryToWriter
    );
  }
};


/**
 * repeated MaterialItem materialItems = 1;
 * @return {!Array<!proto.warehouse.MaterialItem>}
 */
proto.warehouse.SetOrderForMaterialItemsResponse.prototype.getMaterialitemsList = function() {
  return /** @type{!Array<!proto.warehouse.MaterialItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.warehouse.MaterialItem, 1));
};


/** @param {!Array<!proto.warehouse.MaterialItem>} value */
proto.warehouse.SetOrderForMaterialItemsResponse.prototype.setMaterialitemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.warehouse.MaterialItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.warehouse.MaterialItem}
 */
proto.warehouse.SetOrderForMaterialItemsResponse.prototype.addMaterialitems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.warehouse.MaterialItem, opt_index);
};


proto.warehouse.SetOrderForMaterialItemsResponse.prototype.clearMaterialitemsList = function() {
  this.setMaterialitemsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.warehouse.Warehouse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.warehouse.Warehouse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.warehouse.Warehouse.displayName = 'proto.warehouse.Warehouse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.warehouse.Warehouse.prototype.toObject = function(opt_includeInstance) {
  return proto.warehouse.Warehouse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.warehouse.Warehouse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.Warehouse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    capacity: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.warehouse.Warehouse}
 */
proto.warehouse.Warehouse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.warehouse.Warehouse;
  return proto.warehouse.Warehouse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.warehouse.Warehouse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.warehouse.Warehouse}
 */
proto.warehouse.Warehouse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCapacity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.warehouse.Warehouse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.warehouse.Warehouse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.warehouse.Warehouse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.Warehouse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCapacity();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.warehouse.Warehouse.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.warehouse.Warehouse.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.warehouse.Warehouse.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.warehouse.Warehouse.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 capacity = 3;
 * @return {number}
 */
proto.warehouse.Warehouse.prototype.getCapacity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.warehouse.Warehouse.prototype.setCapacity = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.warehouse.MaterialType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.warehouse.MaterialType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.warehouse.MaterialType.displayName = 'proto.warehouse.MaterialType';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.warehouse.MaterialType.prototype.toObject = function(opt_includeInstance) {
  return proto.warehouse.MaterialType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.warehouse.MaterialType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.MaterialType.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.warehouse.MaterialType}
 */
proto.warehouse.MaterialType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.warehouse.MaterialType;
  return proto.warehouse.MaterialType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.warehouse.MaterialType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.warehouse.MaterialType}
 */
proto.warehouse.MaterialType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.warehouse.MaterialType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.warehouse.MaterialType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.warehouse.MaterialType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.MaterialType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.warehouse.MaterialType.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.warehouse.MaterialType.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.warehouse.MaterialType.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.warehouse.MaterialType.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.warehouse.ProductType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.warehouse.ProductType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.warehouse.ProductType.displayName = 'proto.warehouse.ProductType';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.warehouse.ProductType.prototype.toObject = function(opt_includeInstance) {
  return proto.warehouse.ProductType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.warehouse.ProductType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.ProductType.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.warehouse.ProductType}
 */
proto.warehouse.ProductType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.warehouse.ProductType;
  return proto.warehouse.ProductType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.warehouse.ProductType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.warehouse.ProductType}
 */
proto.warehouse.ProductType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.warehouse.ProductType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.warehouse.ProductType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.warehouse.ProductType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.ProductType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.warehouse.ProductType.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.warehouse.ProductType.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.warehouse.ProductType.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.warehouse.ProductType.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.warehouse.MaterialSpecification = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.warehouse.MaterialSpecification, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.warehouse.MaterialSpecification.displayName = 'proto.warehouse.MaterialSpecification';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.warehouse.MaterialSpecification.prototype.toObject = function(opt_includeInstance) {
  return proto.warehouse.MaterialSpecification.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.warehouse.MaterialSpecification} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.MaterialSpecification.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    quantity: jspb.Message.getFieldWithDefault(msg, 2, 0),
    producttype: (f = msg.getProducttype()) && proto.warehouse.ProductType.toObject(includeInstance, f),
    materialtype: (f = msg.getMaterialtype()) && proto.warehouse.MaterialType.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.warehouse.MaterialSpecification}
 */
proto.warehouse.MaterialSpecification.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.warehouse.MaterialSpecification;
  return proto.warehouse.MaterialSpecification.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.warehouse.MaterialSpecification} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.warehouse.MaterialSpecification}
 */
proto.warehouse.MaterialSpecification.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuantity(value);
      break;
    case 3:
      var value = new proto.warehouse.ProductType;
      reader.readMessage(value,proto.warehouse.ProductType.deserializeBinaryFromReader);
      msg.setProducttype(value);
      break;
    case 4:
      var value = new proto.warehouse.MaterialType;
      reader.readMessage(value,proto.warehouse.MaterialType.deserializeBinaryFromReader);
      msg.setMaterialtype(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.warehouse.MaterialSpecification.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.warehouse.MaterialSpecification.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.warehouse.MaterialSpecification} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.MaterialSpecification.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getQuantity();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getProducttype();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.warehouse.ProductType.serializeBinaryToWriter
    );
  }
  f = message.getMaterialtype();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.warehouse.MaterialType.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.warehouse.MaterialSpecification.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.warehouse.MaterialSpecification.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 quantity = 2;
 * @return {number}
 */
proto.warehouse.MaterialSpecification.prototype.getQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.warehouse.MaterialSpecification.prototype.setQuantity = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional ProductType productType = 3;
 * @return {?proto.warehouse.ProductType}
 */
proto.warehouse.MaterialSpecification.prototype.getProducttype = function() {
  return /** @type{?proto.warehouse.ProductType} */ (
    jspb.Message.getWrapperField(this, proto.warehouse.ProductType, 3));
};


/** @param {?proto.warehouse.ProductType|undefined} value */
proto.warehouse.MaterialSpecification.prototype.setProducttype = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.warehouse.MaterialSpecification.prototype.clearProducttype = function() {
  this.setProducttype(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.warehouse.MaterialSpecification.prototype.hasProducttype = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional MaterialType materialType = 4;
 * @return {?proto.warehouse.MaterialType}
 */
proto.warehouse.MaterialSpecification.prototype.getMaterialtype = function() {
  return /** @type{?proto.warehouse.MaterialType} */ (
    jspb.Message.getWrapperField(this, proto.warehouse.MaterialType, 4));
};


/** @param {?proto.warehouse.MaterialType|undefined} value */
proto.warehouse.MaterialSpecification.prototype.setMaterialtype = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.warehouse.MaterialSpecification.prototype.clearMaterialtype = function() {
  this.setMaterialtype(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.warehouse.MaterialSpecification.prototype.hasMaterialtype = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.warehouse.MaterialItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.warehouse.MaterialItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.warehouse.MaterialItem.displayName = 'proto.warehouse.MaterialItem';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.warehouse.MaterialItem.prototype.toObject = function(opt_includeInstance) {
  return proto.warehouse.MaterialItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.warehouse.MaterialItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.MaterialItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    serial: jspb.Message.getFieldWithDefault(msg, 2, ""),
    materialtype: (f = msg.getMaterialtype()) && proto.warehouse.MaterialType.toObject(includeInstance, f),
    warehouse: (f = msg.getWarehouse()) && proto.warehouse.Warehouse.toObject(includeInstance, f),
    orderserial: jspb.Message.getFieldWithDefault(msg, 5, ""),
    materialstate: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.warehouse.MaterialItem}
 */
proto.warehouse.MaterialItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.warehouse.MaterialItem;
  return proto.warehouse.MaterialItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.warehouse.MaterialItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.warehouse.MaterialItem}
 */
proto.warehouse.MaterialItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSerial(value);
      break;
    case 3:
      var value = new proto.warehouse.MaterialType;
      reader.readMessage(value,proto.warehouse.MaterialType.deserializeBinaryFromReader);
      msg.setMaterialtype(value);
      break;
    case 4:
      var value = new proto.warehouse.Warehouse;
      reader.readMessage(value,proto.warehouse.Warehouse.deserializeBinaryFromReader);
      msg.setWarehouse(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderserial(value);
      break;
    case 6:
      var value = /** @type {!proto.warehouse.MaterialState} */ (reader.readEnum());
      msg.setMaterialstate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.warehouse.MaterialItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.warehouse.MaterialItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.warehouse.MaterialItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.warehouse.MaterialItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getSerial();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMaterialtype();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.warehouse.MaterialType.serializeBinaryToWriter
    );
  }
  f = message.getWarehouse();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.warehouse.Warehouse.serializeBinaryToWriter
    );
  }
  f = message.getOrderserial();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getMaterialstate();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.warehouse.MaterialItem.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.warehouse.MaterialItem.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string serial = 2;
 * @return {string}
 */
proto.warehouse.MaterialItem.prototype.getSerial = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.warehouse.MaterialItem.prototype.setSerial = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional MaterialType materialType = 3;
 * @return {?proto.warehouse.MaterialType}
 */
proto.warehouse.MaterialItem.prototype.getMaterialtype = function() {
  return /** @type{?proto.warehouse.MaterialType} */ (
    jspb.Message.getWrapperField(this, proto.warehouse.MaterialType, 3));
};


/** @param {?proto.warehouse.MaterialType|undefined} value */
proto.warehouse.MaterialItem.prototype.setMaterialtype = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.warehouse.MaterialItem.prototype.clearMaterialtype = function() {
  this.setMaterialtype(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.warehouse.MaterialItem.prototype.hasMaterialtype = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Warehouse warehouse = 4;
 * @return {?proto.warehouse.Warehouse}
 */
proto.warehouse.MaterialItem.prototype.getWarehouse = function() {
  return /** @type{?proto.warehouse.Warehouse} */ (
    jspb.Message.getWrapperField(this, proto.warehouse.Warehouse, 4));
};


/** @param {?proto.warehouse.Warehouse|undefined} value */
proto.warehouse.MaterialItem.prototype.setWarehouse = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.warehouse.MaterialItem.prototype.clearWarehouse = function() {
  this.setWarehouse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.warehouse.MaterialItem.prototype.hasWarehouse = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string orderSerial = 5;
 * @return {string}
 */
proto.warehouse.MaterialItem.prototype.getOrderserial = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.warehouse.MaterialItem.prototype.setOrderserial = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional MaterialState materialState = 6;
 * @return {!proto.warehouse.MaterialState}
 */
proto.warehouse.MaterialItem.prototype.getMaterialstate = function() {
  return /** @type {!proto.warehouse.MaterialState} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {!proto.warehouse.MaterialState} value */
proto.warehouse.MaterialItem.prototype.setMaterialstate = function(value) {
  jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * @enum {number}
 */
proto.warehouse.MaterialState = {
  AVAILABLE: 0,
  TAKEN: 1,
  USEDUP: 2
};

goog.object.extend(exports, proto.warehouse);
